### ISSUE TITLE
NullPointerException in SignOnlyFormat with error-prone 2.14.0

### ISSUE THREAD

**Issue by XN137** [KengoTODA/errorprone-slf4j#193]
i tried upgrading to latest error prone release `2.14.0` in our build.
we also use `errorprone-slf4j` at version `0.1.11`
java version is 11

error i was getting:
```
[2022-05-25T09:00:21.147Z]      error-prone version: 2.14.0
[2022-05-25T09:00:21.147Z]      BugPattern: Slf4jSignOnlyFormat
[2022-05-25T09:00:21.147Z]      Stack Trace:
[2022-05-25T09:00:21.147Z]      java.lang.NullPointerException
[2022-05-25T09:00:21.147Z]   	at jp.skypencil.errorprone.slf4j.SignOnlyFormat.matchMethodInvocation(SignOnlyFormat.java:46)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:449)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:746)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:150)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1650)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:433)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:633)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:150)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1460)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:520)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:150)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1032)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:548)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:150)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:560)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:150)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
[2022-05-25T09:00:21.147Z]   	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1418)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1365)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
[2022-05-25T09:00:21.147Z]   	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:75)
[2022-05-25T09:00:21.147Z]   	at jdk.internal.reflect.GeneratedMethodAccessor167.invoke(Unknown Source)
[2022-05-25T09:00:21.147Z]   	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-05-25T09:00:21.147Z]   	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-05-25T09:00:21.147Z]   	at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess0(JavacCompiler.java:626)
[2022-05-25T09:00:21.147Z]   	at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcessWithProperClassloader(JavacCompiler.java:607)
[2022-05-25T09:00:21.147Z]   	at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess(JavacCompiler.java:596)
[2022-05-25T09:00:21.147Z]   	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:178)
[2022-05-25T09:00:21.147Z]   	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1134)
[2022-05-25T09:00:21.147Z]   	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:187)
[2022-05-25T09:00:21.147Z]   	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[2022-05-25T09:00:21.147Z]   	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[2022-05-25T09:00:21.147Z]   	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[2022-05-25T09:00:21.147Z]   	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[2022-05-25T09:00:21.147Z]   	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[2022-05-25T09:00:21.147Z]   	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
[2022-05-25T09:00:21.147Z]   	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:186)
[2022-05-25T09:00:21.147Z]   	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2022-05-25T09:00:21.147Z]   	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2022-05-25T09:00:21.147Z]   	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2022-05-25T09:00:21.147Z]   	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2022-05-25T09:00:21.147Z]   	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2022-05-25T09:00:21.147Z]   	at java.base/java.lang.Thread.run(Thread.java:829)
```

the code where it fails looks like this:
```
class SomeClass {
  (...)

  static {
    logger.info("Debug mode " + (DEBUG ? "enabled." : "disabled."));
  }
}
```

i was unsure whether i should report this here or in the errorprone project.
since the NPE happens in `SignOnlyFormat` i thought this might be the right one.
sorry if i got that wrong :sweat_smile:

**Comment by XN137** [comment]
the issue persists after also upgrading `errorprone-slf4j` to `0.1.12`:
```
[2022-05-26T06:37:01.048Z]      Please report this at https://github.com/google/error-prone/issues/new and include the following:
[2022-05-26T06:37:01.048Z]   
[2022-05-26T06:37:01.048Z]      error-prone version: 2.14.0
[2022-05-26T06:37:01.048Z]      BugPattern: Slf4jSignOnlyFormat
[2022-05-26T06:37:01.048Z]      Stack Trace:
[2022-05-26T06:37:01.048Z]      java.lang.NullPointerException
[2022-05-26T06:37:01.048Z]   	at jp.skypencil.errorprone.slf4j.SignOnlyFormat.matchMethodInvocation(SignOnlyFormat.java:46)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:449)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:746)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:150)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1650)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:433)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:633)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:150)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1460)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:520)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:150)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1032)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:548)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:150)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:560)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:150)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
[2022-05-26T06:37:01.048Z]   	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1418)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1365)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
[2022-05-26T06:37:01.048Z]   	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:75)
```

**Comment by KengoTODA** [comment]
Memo

https://github.com/KengoTODA/errorprone-slf4j/blob/3a1feb2053317274a59aec55184b7889ae16e74b/src/main/java/jp/skypencil/errorprone/slf4j/SignOnlyFormat.java

**Comment by XN137** [comment]
at https://github.com/KengoTODA/errorprone-slf4j/blob/3a1feb2053317274a59aec55184b7889ae16e74b/src/main/java/jp/skypencil/errorprone/slf4j/SignOnlyFormat.java#L42-L46
`ASTHelpers.constValue` evaluates to `null` for the expression `"Debug mode " + (DEBUG ? "enabled." : "disabled.")`
even though it passed the `IS_CONST.matches` check before.

added a test here which is failing:
https://github.com/XN137/errorprone-slf4j/compare/issue-193-reproduction

but this means that core errorprone AST parsing helpers behavior has changed :thinking:
